### ISSUE TITLE
EDT - problèmes avec les surfaces CS incluses dans d'autres surfaces CS

### ISSUE THREAD

**Issue by flombardet** [Tamu/revo#1]
Bonjour,
Lors de la création des EDT, si une surface CS1 est entièrement incluse dans une autre surface CS2 (îlot), la surface CS2 ne prend pas en compte la déduction de la CS1.
Cette erreur implique aussi une erreur sur la surface technique et arrondie de la parcelle. Il faut peut-être faire un contrôle avec le périmètre de la parcelle se situant dans le calque MO_BF

Merci d'avance

**Comment by Tamu** [comment]
Bonjour M. Lombardet,
Merci pour l'information, il y a déjà une analyse qui contrôle le périmètre. La difficulté actuel et de faire un calcul sur des périmètres qui ne sont pas liés (surfaces multiples définit par des polylignes multiples)

Les 2 approches envisagées créer des conflits (périmètre dans le calque MO_BF) voir les functions :

1er étape : [Recherche du périmètre](https://github.com/Tamu/revo/blob/master/R20_x64/Revo/VB/modEDT.vb#L2199)
2ème étape : [Soustraction des îlots](https://github.com/Tamu/revo/blob/master/R20_x64/Revo/VB/modEDT.vb#L2283)

N'hésitez pas à proposer une autre approche.
