### ISSUE TITLE
AutoCAD Map 3D 2016 / Certaines fonction ne se lancent pas

### ISSUE THREAD

**Issue by JUrfer** [Tamu/revo#10]
Bonjour,
Après le passage à un AutoCAD Map 3D 2016 64bits sur le PC de notre apprenti et installation du plugin REVO, certaines commandes ne se lancent pas.
Par exemple l'import Interlis ou pts inscrit les commandes suivantes : 

Commande: -revo Fichier script <#>: #Import;MD01MOVD;[[Space]];*;
Fichier script <#>: #Cmd;ANNOAUTOSCALE|4|_CANNOSCALE|1:500|_CANNOSCALE|1:1000|ANNOAUTOSCALE|-4|ANNOALLVISIBLE|1
Fichier script <#>: #Cmd;regen
Fichier script <#>:

Mais ne fait rien de plus.
L'état descriptif technique cause un plantage de REVO.
J'ai déjà essayé une réinstallation d'AutoCAD et de REVO mais le problème persiste.

Merci d'avance.
Jimmy Urfer
Ingénieur HES en géomatique
Bureau Jaquier Pointet SA

**Comment by Tamu** [comment]
Selon échange, c'est apparemment le même point que le Issue corrigé :
 [#2 Problème ouverture fichier interlis](https://github.com/Tamu/revo/issues/2)
