### ISSUE TITLE
Export de points au format ptp

### ISSUE THREAD

**Issue by flombardet** [Tamu/revo#12]
Lors de l'export de PFP3 (couche MO_PFP3) l'attribut du plan qui est égale à 0 n'est pas inscrit dans le fichier PTP. La valeur 0 est remplacée par une valeur nul (espace).
Fichier exemple en préparation.

**Comment by GRosay** [comment]
> Fichier exemple en préparation.

Bonjour,
Est-ce que le fichier d'exemple est prêt ?

**Comment by flombardet** [comment]
Ci-joint 2 fichiers : 
- 1. Fichier de point au format PTP issu directement de la base de données cadastrale officielle (BDCO) à importer
- 2. Fichier de point exporter avec REVO

[Fichiers exemples PTP.zip](https://github.com/Tamu/revo/files/2322675/Fichiers.exemples.PTP.zip)

**Comment by GRosay** [comment]
Bonjour,
Y a-t-il des paramètres à effectuer avant l'export des points ?
Lorsque je fais l'exporation depuis REVO, je n'obtiens pas du tout le même résultat que dans le deuxième fichier fourni.
Par exemple, pour un point j'obtiens le résultat suivant:

`   271             128 2        2530780.719 1175282.973  475.530                       `

Alors que dans votre export on a ceci:

`01 271             128 2NO  3.2 2530780.719 1175282.973  475.530 O  4.2                `
