### ISSUE TITLE
Erreur de représentation des OD suite à l'import

### ISSUE THREAD

**Issue by flombardet** [Tamu/revo#13]
Les OD « cheminée » sont reportés 2 fois dans les calques suivants : 
- MO_ODL_Conduite, (à mon avis, ne doit pas être reporté dans ce calque)
- MO_ODL_Cheminée.

Les OD « piscine » sont reportés 3 fois. Ils sont reportés dans les calques suivants :
- MO_ODS_Piscine 
- MO_ODS_Piscine_superficie, (à mon avis, ne doit pas être reporté dans ce calque)
- MO_ODL_Piscine_superficie. (à mon avis, ne doit pas être reporté dans ce calque)

Les objets « cheminée » et « piscine » devraient être reporté uniquement dans un calque lors de l’import.

Les fichiers exemples sont en préparation

**Comment by flombardet** [comment]
Ci-joint 2 exemples de fichiers.

Conditions d'utilisations des fichiers : 

- Les géodonnées sont fournies gratuitement par l’OIT et sont totalement dépourvue de la foi publique,
- Elles ont été modifiées afin d’anonymisé la recherche par attribut de localisation,
- Elles ont pour but l’aide au développement du plugin REVO. Tout autre usage est proscrit,
- La propriété des géodonnées, même modifiée, reste à l’Etat de Vaud – Suisse.

[Exemple_cheminée.zip](https://github.com/Tamu/revo/files/2133410/Exemple_cheminee.zip)
[Exemple_piscine.zip](https://github.com/Tamu/revo/files/2133411/Exemple_piscine.zip)

**Comment by GRosay** [comment]
Dans les fichiers interlis d'import, nous avons pour chaque objet un ID qui correspond à un genre (cheminée, conduite, piscine, bât, ...).

Avez-vous une table de correspondance entre les ID et le genre ?
Dans le cas présent, les requêtes de REVO semblent intégré l'ID 15 pour les cheminées mais également pour les conduites, ce qui explique le doublon une fois l'import effectué.

J'ai parcouru la documentation interlis et tous les documents en ma possession mais n'ai malheureusement pas trouvé la table de correspondance.

Par exemple, ci-dessous, le dernier numéro (15) correspond à ce fameux ID.

```
OBJE 8573807 12684646 2 15 @
OBJE 8573811 12684646 2 15 @
OBJE 8578423 12684646 2 15 @
```

**Comment by Tamu** [comment]
Sauf erreur tous ce trouve dans le fichier :
/REVO.bundle/Contents/System/System.db3 (ou éventuellement dans le fichier .xml)

**Comment by GRosay** [comment]
Il n'y a malheureusement pas ces infos dans System.db3 (ni Interlis.db3) et dans le fichier XML de requêtes, les ID sont en dur, sans correspondance.

**Comment by Tamu** [comment]
Donc je pense qu’il faut se reporter au model interlis. De mémoire les ID sont en général un lien provisoire et pas absolu (voir dans le fichier ili)
