### ISSUE TITLE
Gestion des prec_plan

### ISSUE THREAD

**Issue by BureauBelotti** [Tamu/revo#15]
Revo 3.0 contient un problème à l'export de point. L'export de l'attribut PrecPlan doit être revu pour les formats GCO et PTP. Il doit être réalisé sur tous les points: en valeur pour le format GCO et en précision pour le format PTP.

**Comment by BureauBelotti** [comment]
Depuis Revo v3.9, la situation s'est améliorée. Quelques tests sont en cours au bureau à Rolle.

**Comment by BureauBelotti** [comment]
Tests effectués. La fonction est en ordre.

**Comment by GRosay** [comment]
Je ferme le ticket, n'hésitez pas à le rouvrir si le problème resurgit.
