### ISSUE TITLE
Position du No de point avec la fonction "insertion de point"

### ISSUE THREAD

**Issue by BureauBelotti** [Tamu/revo#16]
Revo v2.0: à l'insertion d'un point, le texte du numéro n'est pas toujours positionné horizontalement. Il utilise l'angle mémorisé précédemment par la fonction "insertion de texte".

**Comment by BureauBelotti** [comment]
Revo v3.9 de Practeo: le problème semble résolu. Quelques tests sont en cours au bureau à Rolle.

**Comment by BureauBelotti** [comment]
![revo_v3_9_capture_angle_indesirable_insertionpts](https://user-images.githubusercontent.com/25643521/42025469-ea251a66-7ac4-11e8-8022-84ad7a218bcb.PNG)
Le problème n'est pas résolu. Cela fonctionne parfois mais pas tout le temps ce que l'on peut constater sur l'image ci-jointe.
Les points 4002, 5000 et 5001 sont placés correctement à horizontale alors que les points 4000, 5002 et 5004 ont utilisé un angle de 153. Entre ces 2 séries de points insérés, un angle a été mémorisé automatiquement dans les propriétés du dessin par l'utilisation de la fonction "insertion de textes" de Revo.
Proposition:
lors de l'utilisation de la fonction "insertion de points", il faudrait pouvoir sélectionner si l'on veut utiliser un angle de 100 horizontal par défaut ou utiliser un autre angle.

**Comment by GRosay** [comment]
Bonjour,
Le paramètre de rotation s'enregistre sur le dessin que lorsque l'on fait appel à la fonction "Rotation" de REVO, ce n'est donc pas lié à la fonction insertion de textes.
Il y a donc deux possibilités:
- Soit on ignore la rotation actuelle pour l'insertion des points (on fige à 100 de rotation en permanence)
- Soit un affiche un champ de saisie pour modifier l'angle

Je vous laisse me redire quelle solution vous convient le mieux.

**Comment by BureauBelotti** [comment]
Bonjour M. Rosay,
Je préfère un champ de saisie pour modifier l'angle, avec un choix par défaut à 100. Ainsi, on peut faire des plans pour les CFF par exemple, qui doivent être parallèles à la direction des voies et non orientés par rapport au Nord.
