### ISSUE TITLE
Import Interlis

### ISSUE THREAD

**Issue by ludovicpeguiron** [Tamu/revo#17]
Message d'erreur suivant 
![image](https://user-images.githubusercontent.com/40450753/44442990-a0408480-a5d5-11e8-8e7b-582e34d2c153.png)
lors de l'importation de fichier Interlis. 

Configuration : windows 10 64 bits, Autocad 2018.

**Comment by GRosay** [comment]
Bonjour,
Afin de pouvoir au mieux reproduire et corriger le problème, serait-il possible de me donner plus d'informations sur cette erreure ou de me transmettre un exemple de fichier Interlis provoquant l'erreur ?

Merci

**Comment by ludovicpeguiron** [comment]
Bonjour, vous avez reçu par email ces infos avant la publication de ce poste sur github. N'hésitez pas à me contacter si plus d'infos sont nécessaires.

**Comment by GRosay** [comment]
Bonjour,
Dans quelles circonstances ces erreurs appraîssent-elles ? 
Les avez-vous systématiquement avec le fichier que vous m'avez transmis ?
Je n'ai pas pu reproduire ce problème avec AutoCad 2018 et 2019 en utilisant le fichier.

**Comment by GRosay** [comment]
Bonjour,
Dans quelles circonstances ces erreurs appraîssent-elles ? 
Les avez-vous systématiquement avec le fichier que vous m'avez transmis ?
Je n'ai pas pu reproduire ce problème avec AutoCad 2018 et 2019 en utilisant le fichier.

**Comment by flombardet** [comment]
Pour information,

Je n'ai pas pu reproduire le bug sur mon poste.
Configuration : windows 7 64bits, Autocad 2018, version du plugin PR2018

**Comment by GRosay** [comment]
Problème lié au gabarit de la société Gemetris.
Il manque certains calques ODS rajoutés dans REVO 3.9, listés dans le fichier joint.
[NewCalques.txt](https://github.com/Tamu/revo/files/2383326/NewCalques.txt)
