### ISSUE TITLE
Problème ouverture fichier interlis

### ISSUE THREAD

**Issue by soul-tree-grim** [Tamu/revo#2]
Bonjour,

J'ai un problème d'ouverture de fichier interlis (voir image), quand je clique sur l'onglet importer projet interlis, malheureusement je n'est pas de fenêtre de sélection de fichier qui s'affiche.

Est-ce qu'il y a une autre méthode pour importer les fichiers ou est-ce que j'ai mal installer le plug-in ?

Merci d'avance

![capture-autocadmap-revo](https://cloud.githubusercontent.com/assets/25634341/22731643/a74e7bb8-edeb-11e6-88c2-fe56fe6e51c9.PNG)

**Comment by Tamu** [comment]
Hello,

Il est possible que la variable AutoCAD de navigation est désactivée :
cmd : FILEDIA = 1

Pour plus d'info, peux-tu déplier l'historique des commandes (F2)

**Comment by soul-tree-grim** [comment]
Merci pour ta réactivité !

Alors la cmd de FILEDIA a bien la valeur 1, mais il n'y a toujours pas de fenêtre.

J'ai développer l'historique si ça peux t'aider.

Merci beaucoup pour ton aide.
 
![capture-autocadmap-revo](https://cloud.githubusercontent.com/assets/25634341/22736432/62109dd4-edfe-11e6-9e61-7bce29eabca8.png)

**Comment by Tamu** [comment]
Merci pour la capture d'écran, je n'ai pas l'impression que le problème vient de là !
La commande qui peux être testé : 
`-REVO`
`#Import;MD01MOVD;[[Space]];*;`
`  `

Il est possible qu'il y a un conflit avec AutoCAD Map 2014. C'est une version 64bits ?

**Comment by Tamu** [comment]
Je confirme que la dernière compilation avec AutoCAD Map 2014 64x fonctionne bien.
Conseil : Sauvegarder et supprimer l'ancien dossier plugin. [Détail dans la doc.](https://github.com/Tamu/revo/wiki/Installation-plugin-Revo#mise-%C3%A0-jour-dune-installation-existante)

**Comment by soul-tree-grim** [comment]
C'est bon !

Merci beaucoup pour ton aide, mais j'aurai une autre question concernant l'ouverture des fichier interlis.
J'ai comme extension .ili  c'est normal ?

Parce que il ne reconnais pas ces fichiers là !

Merci d'avance.

**Comment by Tamu** [comment]
Merci d'avoir confirmé la résolution de ce cas.
Concernant l'autre question, j'ai crée un autre "Issue"
