### ISSUE TITLE
Réseau de coordonnées

### ISSUE THREAD

**Issue by ricbarahona** [Tamu/revo#20]
Bonjour, une erreur survient lors de la création du réseau de coordonnées. 
![image](https://user-images.githubusercontent.com/12229813/47220195-614e6580-d3b1-11e8-9039-f40be3e74e25.png)

**Comment by ricbarahona** [comment]
Mon gabarit était corrompu....Tout est ok.

**Comment by Prosopopus** [comment]
J'ai le même problème... Comment avez-vous corrigé votre gabarit de dessin? 

Pierre Potvliege

**Comment by ricbarahona** [comment]
Pardon du retard de ma réponse! J'ai remplacé mon gabarit de base par celui qui est livré dans l'installation de REVO.
