### ISSUE TITLE
Dossier partagé pour V3.0

### ISSUE THREAD

**Issue by BureauBelotti** [Tamu/revo#4]
Lors d'une mise à jour d'une installation existante, peut-on utiliser le dossier partagé existant créé par la version 2.0 ou faut-il aussi le mettre à jour ?

**Comment by Tamu** [comment]
Hello, La seul différence entre la version 2 et 3 est le déplacement du fichier `format.xml` (contenant la configuration des formats d'import/export des points).

Donc oui il est possible d'utiliser le dossier partagé existant. Pour l'activé, il est nécessaire d'ajouter le paramètre `cloudconfig ` dans le fichier `REVO.bundle\Contents\revo-perso.xml` .
Voir documentation : [Configuration Environnement partagé](https://github.com/Tamu/revo/wiki/Environnement-partag%C3%A9#configuration-manuel-)
