### ISSUE TITLE
Problème d'ouverture fichier itf

### ISSUE THREAD

**Issue by soul-tree-grim** [Tamu/revo#6]
Bonjour,

Je rencontre un problème d'ouverture d'un fichier itf (env. 25mb), il reste bloquer à la moitié de l'importation (voir image). 

Est-ce qu'il y a une limite de taille d'importation ? si oui combien ?
Ou est-ce que c'est Autocad qui n'arrive pas à importer ou plutôt qui gère mal ce genre de fichier ?

Merci d'avance pour votre temps et vos réponses.
![bloquage ouverture itf](https://cloud.githubusercontent.com/assets/25634341/23651408/bd5f072a-0325-11e7-9559-60dce164aa8d.png)

**Comment by Tamu** [comment]
Bonjour, je confirme qu'il n'y a pas de limite dans le plugin. La limite est définis dans la mémoire vive disponible par AutoCAD. Plus le fichier est gros, plus le temps d'exécution est long (de manière exponentielle, car les recherches topographies sont élevées à la puissance du nombre d'objet). Je rappelle qu'il n'y a pas de structures de base de donnée geospatial comme dans TopoBase (AutoCAD Map).


Les tests effectués sur un fichier de 25Mb sont concluant et peuvent mettre une nuit de processus.

**Comment by soul-tree-grim** [comment]
Ok merci beaucoup pour la réponse
