### ISSUE TITLE
Installation / poste local

### ISSUE THREAD

**Issue by BureauBelotti** [Tamu/revo#7]
Suite à une installation par défaut (sans l'option dossier partagé) de Revo à partir du site Github  (téléchargement à partir de la branche old-AutoCAD-2010-2014) sur AutoCAD2014 32bits WindowsXP sp3 , je lance AutoCAD2014. Les menu Revo n'apparaissent pas et je dois lancer la commande Revomenu. Revo est alors accessible mais je dois relancer cette commande à chaque démarrage d'AutoCAD ! 
Contrairement à l'aide d'installation, un CD sur le fichier "plugin14.dll" ne comporte pas d'indication de déblocage pour faire revenir le menu Revo.

En essayant la commande "insertion de point", le message suivant apparait:
[Erreur1.pdf](https://github.com/Tamu/revo/files/961864/Erreur1.pdf)
Il s'agit d'un message .net framework object COM !

En essayant un import interlis, le traitement se termine avec succès instantanément mais le dessin est vide !

Merci de me dire ce qu'il faut contrôler pour que l'installation soit correcte, étant donné que j'ai déjà contrôlé la configuration du profil AutoCAD (\support, \actions...) comprenant entre autre le gabarit Revo13.dwt.

**Comment by Tamu** [comment]
Bonjour,

Merci pour la remarque, La branch  'old-AutoCAD-2010-2014' n'est pas compilée pour toute les versions cité. Par exemple s'il y a un besoin pour la version AutoCAD 2014 32bits, il est nécessaire de le compiler et tester avec Microsoft Visual Studio. Cette branch est faite dans un but de sauvegarde/archive.

Propositions de solutions :
a. Installer une nouvelle version d'AutoCAD [(démo gratuite ou abonnement)](https://www.autodesk.fr/products/autocad/free-trial)
b. Faire une compilation pour les anciennes version (avant 2015) : ~ 1 journée de travail

**Comment by BureauBelotti** [comment]
Merci Thomas pour l'info. On va donc privilégier l'installation de Revo avec version AutoCAD dès 2015 sur windows7.
