### ISSUE TITLE
Installation / poste local

### ISSUE THREAD

**Issue by BureauCourdesse** [Tamu/revo#8]
Système Windows 7 Professionnel / 64 bits
AutoCad Map 3D 2012
Suite à l'installation par défaut de Revo à partir du site Github (téléchargement à partir de la branche old-AutoCAD-2010-2014).
Lors de l'ouverture d'AutoCad, le menu revo n'apparaît pas et lorsque je lance la commande "revomenu" il répond commande inconnue.
Les fichiers "plugin**.dll" ne comporte pas d'indication de déblocage.
j'ai essayé les deux installations, en redémarrant mon poste
C:\Program Files\Autodesk\ApplicationPlugins
C:\Users\CARINE\AppData\Roaming\Autodesk\ApplicationPlugins

Merci de votre aide pour résoudre ce problème d'installation.
Carine Loetscher - Ingénieure HES en gestion du territoire
Bureau Coudresse & Associés - Ingénieurs et Géomètres SA

**Comment by Tamu** [comment]
Bonjour,

Pour la réponse voir le [issue n°7](https://github.com/Tamu/revo/issues/7)

Meilleures salutations
Thomas
