### ISSUE TITLE
Installation Revo / AutoCAD 2018

### ISSUE THREAD

**Issue by BureauBelotti** [Tamu/revo#9]
Salut Thomas, j'ai testé l'installation de Revo depuis Github.
Cela fonctionne bien sur Windows7 / AutoCAD 2014-2017 en 64bit.

Dans les "commits" j'ai vu que tu avais apporté des modifications le 28.03.2017 en ajoutant entre autres une référence au "plugin18.dll". Est-ce que tu prévois de rendre Revo compatible AutoCAD 2018 ?

Merci d'avance pour  cette info
Bertrand

**Comment by Tamu** [comment]
Hello Bertrand, Oui je confirme la volonté pour la mise à jour 2018.  Je propose de fermer ce ticket dès que c'est migré

**Comment by BureauBelotti** [comment]
d'accord, merci beaucoup.

**Comment by BureauBelotti** [comment]
Suite à la mise à jour de Revo 3.9 par l'entreprise Practeo, Revo est maintenant compatible avec Autocad 2018 et 2019. On attend encore 1 mois sur des éventuels retours avant de fermer ce ticket.

**Comment by Ryzix** [comment]
Messieurs,
Je suis à la recherche de la fameuse version 3.9 de Revo étant compatible avec AutoCAD 2019. Pouvez-vous m'orienter sur son emplacement/installation?

Merci d'avance

**Comment by Tamu** [comment]
Hello,
Dans l’onglet code, il est nécessaire de changer de branche (voir la dernière en date PR2018)

**Comment by Tamu** [comment]
![0af8a238-4fab-4e0a-9efb-df0d52451177](https://user-images.githubusercontent.com/5020311/46391190-d0eb0200-c6db-11e8-9a89-9f0c9f6bdc7a.jpeg)
